#theme: jekyll-theme-minimal
# Site settings
title: Fatemeh Aarabi, Ph.D.
author:
name: Fati Aarabi
email: faarabi@buffalo.edu
description: ""
github_username: Faarabi
linkedin_uername: faarabi

header_pages:
  - Research.md
  - about.md
  

# Build settings
theme: minima
